# Generated by Django 4.1 on 2022-09-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('chessgames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousChessGame',
            fields=[
                ('chessgame_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chessgames.chessgame')),
                ('black_player', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to='sessions.session')),
                ('white_player', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to='sessions.session')),
            ],
            bases=('chessgames.chessgame',),
        ),
    ]
